name: Create Event Workflow

on:
  create:  # Listens for the create event (branch or tag creation)
    branches:  # Optional filter: only trigger on branch creation
      - "main"
      - "release/*"
    tags:  # Optional filter: only trigger on tags following a specific pattern
      - "v*"

jobs:
  handle-create-event:
    name: Handle Create Event
    runs-on: ubuntu-latest

    steps:
      - name: Display Event Information
        env:
          REF_TYPE: ${{ github.event.ref_type }}  # branch or tag
          REF_NAME: ${{ github.event.ref }}       # name of the branch or tag
          REPO: ${{ github.repository }}
        run: |
          echo "Handling Create Event"
          echo "Ref Type: $REF_TYPE"
          echo "Ref Name: $REF_NAME"
          echo "Repository: $REPO"

      - name: Conditional Action on Branch Creation
        if: ${{ github.event.ref_type == 'branch' }}
        run: echo "A new branch named ${{ github.event.ref }} was created."

      - name: Conditional Action on Tag Creation
        if: ${{ github.event.ref_type == 'tag' }}
        run: echo "A new tag named ${{ github.event.ref }} was created."
