name: Deployment Status Workflow

on:
  deployment_status:
    types: [success, failure, in_progress]  # Listens for deployment status updates

jobs:
  handle-deployment-status:
    name: Handle Deployment Status
    runs-on: ubuntu-latest

    steps:
      - name: Display Deployment Status Information
        env:
          STATUS: ${{ github.event.deployment_status.state }}
          ENVIRONMENT: ${{ github.event.deployment.environment }}
          DEPLOYMENT_URL: ${{ github.event.deployment.url }}
          STATUS_CREATOR: ${{ github.event.sender.login }}
        run: |
          echo "Deployment Status Update"
          echo "Status: $STATUS"
          echo "Environment: $ENVIRONMENT"
          echo "Deployment URL: $DEPLOYMENT_URL"
          echo "Status updated by: $STATUS_CREATOR"

      - name: Conditional Action on Success
        if: ${{ github.event.deployment_status.state == 'success' }}
        run: echo "Deployment to $ENVIRONMENT succeeded. Performing post-deployment tasks."

      - name: Conditional Action on Failure
        if: ${{ github.event.deployment_status.state == 'failure' }}
        run: echo "Deployment to $ENVIRONMENT failed. Notifying the team and rolling back."

      - name: Log In-Progress Status
        if: ${{ github.event.deployment_status.state == 'in_progress' }}
        run: echo "Deployment to $ENVIRONMENT is in progress."
